{% set name = "sqlglot" %}
{% set version = "6.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: a7456d935866ba122610bbaebc5beceea04be5e383cc9b7011aab4d494071e58

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - sqlglot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
