{% set name = "sqlglot" %}
{% set version = "10.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: 9d5218f86477c66f49dde6be90f41b9f663b8db5c2840b20f1bdf86bb9cccce0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - sqlglot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
