{% set name = "sqlglot" %}
{% set version = "28.10.1" %}
{% set ignore_tests = " --ignore=tests/test_optimizer.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_executor.py" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66e0dae43b4bce23314b80e9aef41b8c88fea0e17ada62de095b45262084a8c5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0
    - setuptools_scm
  run:
    - python
  run_constrained:
    - sqlglotrs ==0.12.0

test:
  source_files:
    - tests
  imports:
    - sqlglot
    - sqlglot._typing
    - sqlglot._version
    - sqlglot.dialects
    - sqlglot.diff
    - sqlglot.errors
    - sqlglot.executor
    - sqlglot.expressions
    - sqlglot.generator
    - sqlglot.helper
    - sqlglot.jsonpath
    - sqlglot.lineage
    - sqlglot.optimizer
    - sqlglot.parser
    - sqlglot.planner
    - sqlglot.schema
    - sqlglot.serde
    - sqlglot.time
    - sqlglot.tokens
    - sqlglot.transforms
    - sqlglot.trie
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv {{ ignore_tests }} tests
  requires:
    - pip
    - pytest
    - pytz

about:
  home: https://sqlglot.com
  summary: An easily customizable SQL parser and transpiler
  description: |
    SQLGlot is a no-dependency SQL parser, transpiler, optimizer, and engine. It can be used
    to format SQL or translate between 19 different dialects like DuckDB, Presto, Spark,
    Snowflake, and BigQuery. It aims to read a wide variety of SQL inputs and output
    syntactically correct SQL in the targeted dialects.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - tests/fixtures/jsonpath/LICENSE  # BSD-2-Clause
  dev_url: https://github.com/tobymao/sqlglot
  doc_url: https://sqlglot.com/sqlglot.html

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
