{% set name = "sqlglot" %}
{% set version = "18.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: a64c99d0f512cff05c742b42b2f115327a56d4552ddde821b9158e94da782e36

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python

test:
  imports:
    - sqlglot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  description: |
    SQLGlot is a no-dependency SQL parser, transpiler, optimizer, and engine. It can be used 
    to format SQL or translate between 19 different dialects like DuckDB, Presto, Spark, 
    Snowflake, and BigQuery. It aims to read a wide variety of SQL inputs and output 
    syntactically correct SQL in the targeted dialects.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/tobymao/sqlglot
  doc_url: https://github.com/tobymao/sqlglot/blob/main/README.md

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
