{% set name = "sqlglot" %}
{% set version = "26.3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: 225a3645f1fbff3cdb4bf5ef8c8aea867ddc79b567fc5bc5fd21811875c7099a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python

# duckdb >=0.6 * does not exist (perhaps a typo or a missing channel).
{% set ignore_tests = " --ignore=tests/test_optimizer.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_executor.py" %}

test:
  source_files:
    - tests
  imports:
    - sqlglot
  commands:
    - pip check
    - pytest -v {{ ignore_tests }} tests
  requires:
    - pip
    - pytest
    - pytz

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  description: |
    SQLGlot is a no-dependency SQL parser, transpiler, optimizer, and engine. It can be used
    to format SQL or translate between 19 different dialects like DuckDB, Presto, Spark,
    Snowflake, and BigQuery. It aims to read a wide variety of SQL inputs and output
    syntactically correct SQL in the targeted dialects.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - tests/fixtures/jsonpath/LICENSE # BSD-2-Clause
  dev_url: https://github.com/tobymao/sqlglot
  doc_url: https://github.com/tobymao/sqlglot/blob/main/README.md

extra:
  recipe-maintainers:
    - tobymao
    - thewchan
