{% set name = "sqlglot" %}
{% set version = "4.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglot-{{ version }}.tar.gz
  sha256: e0813e98789f3776b4902407534b95de405c75f172b2119395333c3b9bbb03cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - sqlglot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  summary: An easily customizable SQL parser and transpiler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
